name: Dastardly CI Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://customer.uat.irembopay.com/'  # Replace this with your application URL

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true
